### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by JelleZijlstra** [JelleZijlstra/autotyping#16]
I've put in pretty much all the simple things I can think of, so I think it's time for a release.

**Comment by JelleZijlstra** [comment]
Well, there's already https://pypi.org/project/autotype/ and https://pypi.org/project/autotyper/ on PyPI. Should have checked that before making this repo. I'll have to think of another good name. autoannotator? type-codemod?

**Comment by besfahbod** [comment]
`autotypehinter`?

**Comment by JelleZijlstra** [comment]
I decided to go with `autotyping`.

**Comment by JelleZijlstra** [comment]
https://pypi.org/project/autotyping/21.12.0/ is here
