### ISSUE TITLE
What is the argument for `--safe`?

### ISSUE THREAD

**Issue by gsingh93** [JelleZijlstra/autotyping#44]
```console
$ python -m libcst.tool codemod autotyping.AutotypeCommand --help
...
--safe [SAFE]         Apply all safe transformations
```
What is this argument for? It prevents me from doing `python -m libcst.tool codemod autotyping.AutotypeCommand --safe src_dir`, as `src_dir` is interpreted as the optional argument. Since it's not documented, I'm wondering if it's really necessary.

**Comment by JelleZijlstra** [comment]
Oops, there shouldn't be an argument. For now you can use `--safe 1` or whatever. I'll make it so the flag doesn't take an argument for the next release.
