### ISSUE TITLE
`__contains__` can return other types

### ISSUE THREAD

**Issue by sobolevn** [JelleZijlstra/autotyping#45]
The result of `__contains__` is casted to `bool`.

Examples:

```python
>>> class A:
...     def __contains__(self, other):
...         return other
... 
>>> 'abc' in A()
True
>>> None in A()
False
```

So, technically `-> bool` is not correct 🤔

**Comment by JelleZijlstra** [comment]
And technically `__len__` can return `int | SupportsIndex`. I think within the scope of this project, returning `bool` is fine because that's what `__contains__` is supposed to return.
