### ISSUE TITLE
type checker?

### ISSUE THREAD

**Issue by jakkdl** [JelleZijlstra/autotyping#48]
Heya,
gonna start working on #46 and wanna set up my dev environment properly. The code looks well typed, but tox doesn't have any type check set up and I don't see any config for mypy/pyright/other. I could add one, but the code doesn't currently pass mypy (even w/o `--strict`) and pyright (which tends to be more lenient) also gives one error. So I'd wanna know what program you've been using to type check with before proceeding with anything in that direction.

**Comment by JelleZijlstra** [comment]
It's typechecked with pyanalyze (`tox -e pyanalyze`).

**Comment by jakkdl** [comment]
ah, silly me to think I was aware of all the type checkers in use :sweat_smile:
