### ISSUE TITLE
Cant run the module 

### ISSUE THREAD

**Issue by ClementDelannoySlateDigital** [JelleZijlstra/autotyping#71]
```
 python -m autotyping .
No module named autotyping.__main__; 'autotyping' is a package and cannot be directly executed
```

Too bad, I'd love to modernize that dirty code

I'm on macOS Sonoma, trying to run it on the VSCode terminal. Same result in ITerm.
I tried on a fresh new venv 

```
python -m venv venv
source venv/bin/activate
pip install autotyping
python -m autotyping . 
```
And I got the same result

Thanks! 
Clement

**Comment by JelleZijlstra** [comment]
This should be fixed in the next release, which I'll cut very soon.

**Comment by JelleZijlstra** [comment]
autotyping 24.3.0, which was just released, fixes this.

**Comment by ClementDelannoySlateDigital** [comment]
Perfect, thanks a lot! Great tool by the way, it will help a lot :)
