### ISSUE TITLE
Add pre-commit support?

### ISSUE THREAD

**Issue by exitflynn** [JelleZijlstra/autotyping#75]
I've discovered the project pretty recently and find it really neat! I've been using it as a local pre-commit hook for a while and I think it could benefit from having [pre-commit](https://pre-commit.com/) support? (discussions in a similar vein in other projects was originally how i found out about `autotyping` in the first place haha)

**Comment by JelleZijlstra** [comment]
I'd be happy to take a PR adding a pre-commit hook and/or documentation for how to integrate the tool with pre-commit.
